#!/usr/bin/env bash
# OWIsMind PreToolUse guardrail — deterministic safety net (belt-and-suspenders with settings.json).
# Reads the hook payload (JSON) on stdin. To BLOCK a tool call: print a reason to stderr and exit 2.
# Pure bash + grep on the raw JSON payload — no jq/python dependency, so it never breaks a session.
#
# Rules enforced:
#   1. NO INSTALL — agents must never install dependencies; only the user does. Safety first.
#   2. Generated outputs (resource/owismind-app/, ready-for-dataiku/) must not be hand-edited.
#   3. Soft reminder about Dataiku-instance safety on backend code.
set -uo pipefail

payload="$(cat)"

# Block and tell Claude why (exit 2 feeds stderr back to the model).
block() {
  echo "BLOCKED by OWIsMind guardrail: $1" >&2
  exit 2
}

# --- Rule 1: forbid any package install (matches the "command" field of a Bash call) ---
if printf '%s' "$payload" | grep -Eiq '"command"[[:space:]]*:[^}]*(npm[[:space:]]+(install|ci|add|update)|npm[[:space:]]+i[[:space:]"]|yarn[[:space:]]+(add|install)|pnpm[[:space:]]+(add|install|i[[:space:]"])|pip3?[[:space:]]+install|pipenv[[:space:]]+install|poetry[[:space:]]+(add|install)|conda[[:space:]]+install|brew[[:space:]]+install|npx[[:space:]])'; then
  block "package installs are forbidden for agents. Ask the user to run it manually — only the user installs dependencies (safety first)."
fi

# --- Rule 2: forbid manual edits of build/package OUTPUTS (they are generated) ---
if printf '%s' "$payload" | grep -Eq '"file_path"[[:space:]]*:[^,}]*(resource/owismind-app|ready-for-dataiku)'; then
  block "this path is GENERATED by build/package. Edit frontend/src, python-lib/ or webapps/ then run /build-plugin or /package-plugin instead of hand-editing the output."
fi

# --- Rule 3 (non-blocking): remind about instance safety when touching backend Python ---
if printf '%s' "$payload" | grep -Eq '"file_path"[[:space:]]*:[^,}]*(python-lib|webapps/[^"]*backend\.py)'; then
  echo "OWIsMind reminder: backend code runs on the Dataiku instance. Keep it safe (no heavy/blocking/overloading work), use SQL direct with PROJECT_KEY prefix + COMMIT + parametrized queries, no generic SQL route, server-side agent whitelist." >&2
fi

exit 0
