"""DSS-free tests of the owismind_factory pure logic + a full dry-run pipeline.

No dataiku import anywhere at factory module level, so the package imports
cleanly. The pipeline dry-run uses a FakeProject exposing only the read-only
listing surface; every mutating closure must NOT run in dry-run mode.
"""

import os
import sys
import unittest

_HERE = os.path.dirname(os.path.abspath(__file__))
_MIRROR = os.path.dirname(_HERE)
_LIB = os.path.join(_MIRROR, "project-library", "python")
if _LIB not in sys.path:
    sys.path.insert(0, _LIB)

from owismind_factory import agent_builder, pipeline, tool_builder, wizard  # noqa: E402
from owismind_factory.fctx import FactoryContext, PLANNED, MANUAL  # noqa: E402
from owismind_factory.spec import DomainSpec, SpecError  # noqa: E402


class TestDomainSpec(unittest.TestCase):
    def test_derived_names(self):
        spec = DomainSpec(domain="satisfaction", base_dataset="CX_Surveys",
                          label_fr="Expert satisfaction", label_en="Satisfaction expert")
        self.assertEqual(spec.profile_dataset, "CX_Surveys_profile")
        self.assertEqual(spec.value_index_dataset, "CX_Surveys_value_index")
        self.assertEqual(spec.value_catalog_dataset, "CX_Surveys_value_catalog")
        self.assertEqual(spec.scenario_name, "Refresh_Satisfaction")
        self.assertEqual(spec.capability_key, "satisfaction_expert")
        self.assertEqual(spec.orchestrator_tool_name, "ask_satisfaction_expert")
        self.assertEqual(spec.semantic_model_name, "CX_Surveys_Semantic_Model")

    def test_bad_domain_rejected(self):
        with self.assertRaises(SpecError):
            DomainSpec(domain="Satisfaction!", base_dataset="X",
                       label_fr="a", label_en="b")

    def test_long_dataset_name_rejected(self):
        with self.assertRaises(SpecError):
            DomainSpec(domain="x_ray", base_dataset="A" * 45,
                       label_fr="a", label_en="b")

    def test_source_requires_connection_and_table(self):
        with self.assertRaises(SpecError):
            DomainSpec(domain="x_ray", base_dataset="Xr",
                       label_fr="a", label_en="b", source={"connection": "SQL_owi"})

    def test_roundtrip(self):
        spec = DomainSpec(domain="x_ray", base_dataset="Xr", label_fr="a", label_en="b",
                          source={"connection": "SQL_owi", "table": "t"})
        again = DomainSpec.from_dict(spec.to_dict())
        self.assertEqual(again.to_dict(), spec.to_dict())


class TestFactoryContext(unittest.TestCase):
    def test_dry_run_never_executes(self):
        ctx = FactoryContext(project=object(), dry_run=True)
        calls = []
        result = ctx.act("s", "d", lambda: calls.append(1))
        self.assertIsNone(result)
        self.assertEqual(calls, [])
        self.assertEqual(ctx.actions[0]["status"], PLANNED)

    def test_failure_recorded_not_raised(self):
        ctx = FactoryContext(project=object(), dry_run=False, abort_on_failure=False)

        def boom():
            raise RuntimeError("boom")

        self.assertIsNone(ctx.act("s", "d", boom))
        self.assertTrue(ctx.has_failures())

    def test_failure_raises_when_aborting(self):
        ctx = FactoryContext(project=object(), dry_run=False, abort_on_failure=True)
        with self.assertRaises(RuntimeError):
            ctx.act("s", "d", lambda: (_ for _ in ()).throw(RuntimeError("boom")))


class TestAgentCodeGeneration(unittest.TestCase):
    """Generation against the REAL engine file: the strongest template test."""

    @classmethod
    def setUpClass(cls):
        cls.template = open(os.path.join(_MIRROR, "GenAI", "Agents",
                                         "SalesDrive_revenue_expert.py")).read()
        cls.spec = DomainSpec(domain="satisfaction", base_dataset="CX_Surveys",
                              label_fr="Expert satisfaction", label_en="Satisfaction expert")

    def test_constants_swapped(self):
        code = agent_builder.generate_subagent_code(self.template, self.spec, "toolXYZ")
        self.assertIn('PROFILE_DATASET = "CX_Surveys_profile"', code)
        self.assertIn('VALUE_INDEX_DATASET = "CX_Surveys_value_index"', code)
        self.assertIn('SEMANTIC_TOOL_ID = "toolXYZ"', code)
        self.assertIn('SEMANTIC_TOOL_NAME = "satisfaction_semantic_query"', code)
        self.assertNotIn('PROFILE_DATASET = "DRIVE_Revenues_profile"', code)
        self.assertIn("GENERATED by owismind_factory", code)

    def test_engine_body_untouched(self):
        code = agent_builder.generate_subagent_code(self.template, self.spec, "toolXYZ")
        # Frozen dialect + engine landmarks survive generation verbatim.
        for landmark in ("KNOWN_BLOCK_IDS", "KNOWN_TOOL_NAMES", "AGENT_RESULT",
                         "semantic-model-query", "def build_understand_prompt"):
            self.assertIn(landmark, code)

    def test_missing_tool_id_gets_placeholder(self):
        code = agent_builder.generate_subagent_code(self.template, self.spec, "")
        self.assertIn('SEMANTIC_TOOL_ID = "FILL_ME_TOOL_ID"', code)

    def test_template_drift_detected(self):
        broken = self.template.replace('SEMANTIC_TOOL_NAME = "', 'SEMANTIC_TOOL_NAME_X = "')
        with self.assertRaises(agent_builder.TemplateDriftError):
            agent_builder.generate_subagent_code(broken, self.spec, "t")


class TestWizardPure(unittest.TestCase):
    def test_prompt_contains_profile_and_rules(self):
        prompt = wizard.build_draft_prompt("DIGEST_TEXT", "CX_Surveys", "satisfaction",
                                           answers={"time_column": "d"})
        self.assertIn("DIGEST_TEXT", prompt)
        self.assertIn("HUMAN ANSWERS", prompt)
        self.assertIn("__TABLE__", prompt)
        self.assertNotIn("\u2014", prompt)
        self.assertNotIn("\u2013", prompt)

    def test_digest_truncated(self):
        profile = {"__dataset__": {"a": 1}}
        for index in range(500):
            profile["col%d" % index] = {"description": "x" * 200}
        digest = wizard.build_profile_digest(profile, "DS")
        self.assertLessEqual(len(digest), wizard.MAX_DIGEST_CHARS + 30)

    def test_merge_answers_time_and_metric(self):
        config = wizard.merge_answers({"profile_overrides": []},
                                      {"time_column": "creationDate",
                                       "default_metric": "ticket_count"})
        fields = {(o["key"], o["field"]) for o in config["profile_overrides"]}
        self.assertIn(("__dataset__", "time"), fields)
        self.assertIn(("__dataset__", "default_metric"), fields)

    def test_substitute_golden_tables(self):
        config = {"golden_queries": [
            {"question": "q1", "sql": 'SELECT 1 FROM __TABLE__'},
            {"question": "q2"},
        ]}
        ready, todo = wizard.substitute_golden_tables(config, '"PROJ_tbl"')
        self.assertEqual(len(ready), 1)
        self.assertIn('"PROJ_tbl"', ready[0]["generatedSql"])
        self.assertEqual(len(todo), 1)


class TestToolBuilderPure(unittest.TestCase):
    def test_deep_model_id_swap(self):
        params = {"a": "ref/AHUh9hb/x", "b": [{"c": "AHUh9hb"}], "d": 3}
        swapped = tool_builder._swap_model_id(params, "AHUh9hb", "NEW1234")
        self.assertEqual(swapped["a"], "ref/NEW1234/x")
        self.assertEqual(swapped["b"][0]["c"], "NEW1234")
        self.assertEqual(swapped["d"], 3)


class _FakeFlow(object):
    def list_zones(self):
        return []


class _FakeProject(object):
    """Read-only listing surface only: any mutating call would raise."""
    project_key = "FAKE_PROJECT"

    def list_datasets(self):
        return []

    def list_recipes(self):
        return []

    def list_scenarios(self, as_type="listitems"):
        return []

    def get_flow(self):
        return _FakeFlow()

    def get_dataset(self, name):
        raise RuntimeError("read of dataset %s not available in this fake" % name)

    def list_agent_tools(self):
        raise RuntimeError("no tools in fake")

    def list_agents(self):
        raise RuntimeError("no agents in fake")

    def list_semantic_models(self):
        raise RuntimeError("no models in fake")

    def get_library(self):
        raise RuntimeError("no library in fake")


class TestPipelineDryRun(unittest.TestCase):
    def test_full_dry_run_plans_without_touching_dss(self):
        spec = DomainSpec(domain="satisfaction", base_dataset="CX_Surveys",
                          label_fr="Expert satisfaction", label_en="Satisfaction expert",
                          source={"connection": "SQL_owi", "schema": "public",
                                  "table": "cx_surveys"})
        ctx = FactoryContext(project=_FakeProject(), dry_run=True)
        pipeline.create_domain(ctx, spec)
        statuses = {a["status"] for a in ctx.actions}
        self.assertFalse(ctx.has_failures(), ctx.actions)
        self.assertIn(PLANNED, statuses)
        self.assertIn(MANUAL, statuses)
        steps = [a["step"] for a in ctx.actions]
        for expected in ("source_dataset", "zone", "scenario", "semantic_model",
                         "capability", "smoke_checklist", "first_build"):
            self.assertIn(expected, steps, "missing step %s in %s" % (expected, steps))
        # The gated steps degrade to manual/planned, never fail, in dry-run.
        report = ctx.report_markdown()
        self.assertIn("DRY RUN", report)


if __name__ == "__main__":
    unittest.main()
