"""Code Agent generation and creation (creation is GATED: needs Phase 0 hints).

Two independent halves:

1. generate_subagent_code(): PURE text transformation. The dataset-expert engine
   (agents/SalesDrive_revenue_expert.py, uploaded to the hub as
   templates/dataset_expert.py) is dataset-agnostic by design: its whole domain
   binding is the CONFIG header. The generator rewrites exactly those constants
   and refuses to proceed if any expected constant is not found exactly once
   (template drift protection).

2. create_code_agent(): ``project.create_agent(name, "PYTHON_AGENT")`` is
   official client API, but the raw layout of a Code Agent version's settings
   (where the source code and the code env live inside
   ``versions[*].pythonAgentSettings``) is NOT documented. So code injection is
   gated behind ``schema_hints`` produced by the Phase 0 probe from the LIVE
   orchestrator agent. Without hints, the factory writes the generated file to
   the hub (generated/<Agent>.py) and reports the one manual paste step.
"""

import re

from . import hub as hub_module

# CONFIG constants rewritten in the engine template. Each regex must match
# EXACTLY ONCE, else the template has drifted and we stop instead of guessing.
_CONFIG_PATTERNS = {
    "PROFILE_DATASET": r'^PROFILE_DATASET = "[^"]*"',
    "VALUE_INDEX_DATASET": r'^VALUE_INDEX_DATASET = "[^"]*"',
    "SEMANTIC_TOOL_ID": r'^SEMANTIC_TOOL_ID = "[^"]*"',
    "SEMANTIC_TOOL_NAME": r'^SEMANTIC_TOOL_NAME = "[^"]*"',
}


class TemplateDriftError(RuntimeError):
    """The engine template no longer matches the generator's expectations."""


def generate_subagent_code(template_code, spec, tool_id, deploy_project=None):
    """Rewrite the engine template's CONFIG header for a new domain (pure).

    :param str template_code: full source of the dataset-expert engine.
    :param spec: DomainSpec.
    :param str tool_id: the domain's Semantic Model Query tool id ("" = fill later).
    :param str deploy_project: project key stamped into the deploy banner.
    """
    replacements = {
        "PROFILE_DATASET": 'PROFILE_DATASET = "%s"' % spec.profile_dataset,
        "VALUE_INDEX_DATASET": 'VALUE_INDEX_DATASET = "%s"' % spec.value_index_dataset,
        "SEMANTIC_TOOL_ID": 'SEMANTIC_TOOL_ID = "%s"' % (tool_id or "FILL_ME_TOOL_ID"),
        "SEMANTIC_TOOL_NAME": 'SEMANTIC_TOOL_NAME = "%s"' % spec.semantic_tool_name,
    }
    code = template_code
    for key, pattern in _CONFIG_PATTERNS.items():
        matches = re.findall(pattern, code, flags=re.MULTILINE)
        if len(matches) != 1:
            raise TemplateDriftError(
                "expected exactly one %s assignment in the engine template, found %d: "
                "the template drifted, update owismind_factory/agent_builder.py "
                "together with the engine" % (key, len(matches)))
        code = re.sub(pattern, replacements[key].replace("\\", "\\\\"), code,
                      count=1, flags=re.MULTILINE)

    banner = (
        "# ============================================================\n"
        "# GENERATED by owismind_factory for domain %r\n"
        "# Engine: dataset_expert template (SalesDrive_revenue_expert engine).\n"
        "# DEPLOY TARGET: project %s / Code Agent %s (env 3.11).\n"
        "# Review the CONFIG block below, then paste into the DSS Code Agent.\n"
        "# ============================================================\n"
        % (spec.domain, deploy_project or "<current project>", spec.agent_name))
    return banner + code


def load_engine_template(project):
    """The engine template text from the hub (uploaded by 01_push_config_hub)."""
    return hub_module.read_text(project, hub_module.TEMPLATE_AGENT_PATH)


# --------------------------------------------------------------------- creation

def read_agent_raw(project, agent_id):
    """Full raw settings of an agent (read-only; the probe's discovery source)."""
    agent = project.get_agent(agent_id)
    settings = agent.get_settings()
    return settings.get_raw()


def _resolve_version(raw):
    versions = raw.get("versions") or []
    if not versions:
        raise RuntimeError("agent has no versions in its raw settings")
    active = raw.get("activeVersion")
    for version in versions:
        if version.get("versionId") == active:
            return version
    return versions[-1]


def agent_exists(project, name):
    try:
        for item in project.list_agents():
            item_name = item.name if hasattr(item, "name") else item.get("name")
            if item_name == name:
                return item.id if hasattr(item, "id") else item.get("id")
    except Exception:
        pass
    return None


def paste_checklist(spec, generated_path):
    return (
        "Create the Code Agent BY HAND in DSS (one paste): Agents & GenAI Models > "
        "New Agent > Code Agent, name %s, Settings tab: select the Python 3.11 code "
        "env; Code tab: paste the generated file from the project library %s; save. "
        "Then note the agent id (agent:XXXX) into the capability entry."
        % (spec.agent_name, generated_path))


def create_code_agent(ctx, spec, code, schema_hints, code_env=""):
    """Create the Code Agent and inject the generated code (gated).

    :param dict schema_hints: produced by probes.run_read_probes /
        run_write_probes. Expected keys:
        - "internal_key": the per-type settings key (e.g. "pythonAgentSettings"),
        - "code_key": the key holding the Python source inside it,
        - "env_template": optional dict merged into the internal settings to
          select the 3.11 code env (copied from a live agent by the probe).
    Returns "agent:<id>" or None.
    """
    existing_id = agent_exists(ctx.project, spec.agent_name)
    if existing_id:
        ctx.skip("code_agent", "agent %s already exists (id %s)" % (spec.agent_name, existing_id))
        return "agent:%s" % existing_id

    generated_path = "%s/generated/%s.py" % (hub_module.HUB_ROOT, spec.agent_name)

    gated = (not schema_hints or not schema_hints.get("internal_key")
             or not schema_hints.get("code_key"))
    if gated:
        # Fallback: persist the generated code where a human can copy it in one click.
        ctx.act("code_agent_file",
                "write generated agent code to the project library %s" % generated_path,
                lambda: hub_module.write_text(ctx.project, generated_path, code))
        ctx.manual("code_agent",
                   "GATED (the Code Agent raw settings schema is not probe-confirmed). "
                   + paste_checklist(spec, generated_path))
        return None

    def _create():
        agent = ctx.project.create_agent(spec.agent_name, "PYTHON_AGENT")
        settings = agent.get_settings()
        raw = settings.get_raw()
        version = _resolve_version(raw)
        internal = version.get(schema_hints["internal_key"])
        if internal is None:
            internal = {}
            version[schema_hints["internal_key"]] = internal
        internal[schema_hints["code_key"]] = code
        env_template = schema_hints.get("env_template")
        if isinstance(env_template, dict):
            for key, value in env_template.items():
                internal[key] = value
        settings.save()
        # Never wake the agent up automatically (that starts backend compute):
        # the smoke step reports status only.
        return "agent:%s" % agent.id

    result = ctx.act("code_agent",
                     "create Code Agent %s (PYTHON_AGENT) and inject %d chars of "
                     "generated code via probe-confirmed keys %s.%s%s"
                     % (spec.agent_name, len(code), schema_hints["internal_key"],
                        schema_hints["code_key"],
                        ", code env template applied" if schema_hints.get("env_template") else
                        " (code env: set it in the DSS Settings tab, hint not provided)"),
                     _create)
    if result is None and not ctx.dry_run:
        # Creation failed: fall back to the manual paste path so the night's
        # work is still usable.
        ctx.act("code_agent_file",
                "write generated agent code to the project library %s (fallback)" % generated_path,
                lambda: hub_module.write_text(ctx.project, generated_path, code))
        ctx.manual("code_agent", paste_checklist(spec, generated_path))
    return result
